---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp
  labels:
    id: C0928109
    app: wp-app
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      id: C0928109
  template:
    metadata:
      labels:
        id: C0928109
        app: wp-app
        env: dev
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb.db.svc.cluster.local
            - name: WORDPRESS_DB_USER
              value: db_user
            - name: WORDPRESS_DB_PASSWORD
              value: db_password
            - name: WORDPRESS_DB_NAME
              value: wordpress

