---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: db
type: Opaque
data:
  MYSQL_ROOT_PASS: cm9vdF9wYXNzd29yZA==
  WORDMYSQL_DATABASE: d29yZHByZXNz
  MYSQL_USER: ZGJfdXNlcg==
  MYSQL_PASSWORD: ZGJfcGFzc3dvcmQ=
