---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: proxy
  labels:
    id: C0928109
    app: proxy
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      id: C0928109
  template:
    metadata:
      labels:
        id: C0928109
        app: proxy
        env: dev
    spec:
      containers:
        - name: nginx-proxy
          image: <dockerhub-username>/nginx-proxy:latest
          ports:
            - containerPort: 80
